export const APPLICATION_STATUS = {
  PENDING: 'PENDING',
  AWAITING_REFERENCES: 'AWAITING_REFERENCES',
  UNDER_REVIEW: 'UNDER_REVIEW',  
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const;

export type ApplicationStatus = typeof APPLICATION_STATUS[keyof typeof APPLICATION_STATUS];

export const STATUS_DISPLAY_NAMES = {
  [APPLICATION_STATUS.PENDING]: 'Pending',
  [APPLICATION_STATUS.AWAITING_REFERENCES]: 'Awaiting References',
  [APPLICATION_STATUS.UNDER_REVIEW]: 'Under Review',
  [APPLICATION_STATUS.INTERVIEW_SCHEDULED]: 'Interview Scheduled',
  [APPLICATION_STATUS.APPROVED]: 'Approved',  
  [APPLICATION_STATUS.REJECTED]: 'Rejected'
} as const;

export const STATUS_OPTIONS = [
  { value: APPLICATION_STATUS.PENDING, label: STATUS_DISPLAY_NAMES[APPLICATION_STATUS.PENDING] },
  { value: APPLICATION_STATUS.AWAITING_REFERENCES, label: STATUS_DISPLAY_NAMES[APPLICATION_STATUS.AWAITING_REFERENCES] },
//   { value: APPLICATION_STATUS.UNDER_REVIEW, label: STATUS_DISPLAY_NAMES[APPLICATION_STATUS.UNDER_REVIEW] },
  { value: APPLICATION_STATUS.INTERVIEW_SCHEDULED, label: STATUS_DISPLAY_NAMES[APPLICATION_STATUS.INTERVIEW_SCHEDULED] },
  { value: APPLICATION_STATUS.APPROVED, label: STATUS_DISPLAY_NAMES[APPLICATION_STATUS.APPROVED] },
  { value: APPLICATION_STATUS.REJECTED, label: STATUS_DISPLAY_NAMES[APPLICATION_STATUS.REJECTED] }
];

export const REFERENCE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED', 
  REJECTED: 'REJECTED'
} as const;

export type ReferenceStatus = typeof REFERENCE_STATUS[keyof typeof REFERENCE_STATUS];
